### ISSUE TITLE
hypevol.h missing

### ISSUE THREAD

**Issue by costashatz** [resibots/limbo#101]
`hv/hypervol.h` is missing, but required from [here](https://github.com/resibots/limbo/blob/master/src/limbo/experimental/stat/hyper_volume.hpp#L6) (experimental).

@jbmouret you probably forgot to add it..

**Comment by jbmouret** [comment]
This is here: https://github.com/resibots/limbo/pull/102

But why didn't we see this before?

**Comment by costashatz** [comment]
> But why didn't we see this before?

Most probably you had it in your machine and we never re-compiled the experimental stuff..

**Comment by costashatz** [comment]
Maybe we should have in travis one configuration building the experimental things.. What do you say?

**Comment by jbmouret** [comment]
I mean, why are you suddenly compiling something that was not compiled
before? Are we missing other issues like this?

**Comment by jbmouret** [comment]
I think we should. This should at least compile...

**Comment by costashatz** [comment]
> I mean, why are you suddenly compiling something that was not compiled
> before?

I compiled the experimental things, because you changed IMGPO and I wanted to see how it works with the hyperparameter optimization..

> Are we missing other issues like this?

That's what we are trying to catch with the travis builds and with the extensive_tests (that should be compiling on the cluster once every month?)

**Comment by jbmouret** [comment]
The cron is not ready yet (I need to install a SMTP server first).

**Comment by costashatz** [comment]
> The cron is not ready yet (I need to install a SMTP server first).

But still that's the idea. We have `travis` builds to catch most of them and the `extensive ones` to catch more detailed/rare ones..

**Comment by costashatz** [comment]
Anyway, this issue is fixed by #102 . Closing...
