### ISSUE TITLE
Saving more information to logging directory

### ISSUE THREAD

**Issue by jrieffel** [resibots/limbo#106]
While samples.dat and aggregated_observations.dat are valuable, it may also be worth saving a log file with the specific limbo parameters (samples, iterations, optimizer, kernel, etc) used for that limbo run.

**Comment by costashatz** [comment]
You can always create your own logging struct. See [here](http://www.resibots.eu/limbo/api.html#statistics-stats) for more details.

**Comment by jrieffel** [comment]
thanks, I'll try that!

**Comment by jbmouret** [comment]
And for the parameters, you can use the BO_PARAMS macro. See mono_dim.cpp
for an example.

**Comment by jbmouret** [comment]
We should write a short tutorial about this! I will try to do it during my
flight tomorrow.

**Comment by costashatz** [comment]
I think this was answered in #109 ! Closing...
