### ISSUE TITLE
remove tools/clean_code.py and tools/rtags_index.py?

### ISSUE THREAD

**Issue by jbmouret** [resibots/limbo#108]
What is the state of these script? should we remove them? or should we document them? Does someone use them?

**Comment by costashatz** [comment]
I cannot see any `tools/rtags_index.py` file.. For the `clean_code.py`, I think we should discuss it at the next meeting.. Probably we will keep the one in the separate repo: https://github.com/resibots/format_code

**Comment by costashatz** [comment]
@dogoepp what should we do with the `clean_code.py` file? See also #98 ...

**Comment by dogoepp** [comment]
I need to give this a look.

**Comment by costashatz** [comment]
@dogoepp any updates on this one?

**Comment by costashatz** [comment]
Same as #98 ... **Closing...**
