### ISSUE TITLE
src/example/gp.cpp is not compiled (and probably do not compile anymore)

### ISSUE THREAD

**Issue by jbmouret** [resibots/limbo#111]
I think the result of the query should be changed, at least.

**Comment by costashatz** [comment]
There's no such file anymore.. I think you should clean your repo..

**Comment by jbmouret** [comment]
Oops. Sorry. But why has this file been deleted?

**Comment by costashatz** [comment]
I went to the initial commit (https://github.com/resibots/limbo/tree/3d8ce5117c54ca7e1ec27cc7fc1baff228e23fce) and I cannot really find the file. I, also, tried some random commits in the middle and didn't find the file. Can you show it to us here?

**Comment by costashatz** [comment]
@jbmouret any feedback on this one?

**Comment by jbmouret** [comment]
OK. It may have been mine :)


It was something simple. I will make it compile and put it back.

**Comment by costashatz** [comment]
OK... So I am closing this issue...
