### ISSUE TITLE
Issue(s) with random number generation

### ISSUE THREAD

**Issue by jbmouret** [resibots/limbo#113]
I just discovered two important issues with random_generation. 

First, ```init::random_sampling``` uses ```tools::random_vector()```, which does not use our C++11 random number generator. Instead, it uses ```Eigen::Random()```, which uses the C rand() call. **This means that srand(something_random) needs to be called in the main() function**. Should we just add these calls, or should we switch tools::random_vector() to a better defined random number generator? Has this been done with the benchmarks?

Second, ```std::random_device()```, which we use in our random number generator, might not always be random (depending on the platform and the compiler). See: http://stackoverflow.com/questions/18880654/why-do-i-get-the-same-sequence-for-every-run-with-stdrandom-device-with-mingw

Also: http://www.pcg-random.org/posts/cpps-random_device.html

Should we replace it with something?

**Comment by costashatz** [comment]
> First, init::random_sampling uses tools::random_vector(), which does not use our C++11 random number generator. Instead, it uses Eigen::Random(), which uses the C rand() call. This means that srand(something_random) needs to be called in the main() function. Should we just add these calls, or should we switch tools::random_vector() to a better defined random number generator?

I vote to use the same generator we are using for all our other random numbers and not Eigen's. That way we control it better..

> Has this been done with the benchmarks?

It should; we are using random sampling. But I am not sure it will affect our performance. We did test it in different machines. We should fix this issue though..

> Second, std::random_device(), which we use in our random number generator, might not always be random (depending on the platform and the compiler). See: http://stackoverflow.com/questions/18880654/why-do-i-get-the-same-sequence-for-every-run-with-stdrandom-device-with-mingw
> 
> Also: http://www.pcg-random.org/posts/cpps-random_device.html
> 
> Should we replace it with something?

We could seed the random_device each time is created: `rng.seed(seed_val);`..

**Comment by jbmouret** [comment]
In that case we can seed the RNG and not the random device... the whole
point of using std::random_device was to have a portable way to use a good
seed (e.g. /dev/random or intel's random instructions).

**Comment by costashatz** [comment]
> In that case we can seed the RNG and not the random device... the whole
> point of using std::random_device was to have a portable way to use a good
> seed (e.g. /dev/random or intel's random instructions).

Then, I suggest to leave it as it is... I would assume that in most cases we will have random numbers, right?

**Comment by costashatz** [comment]
Another option would be to use `Boost`'s random numbers...

**Comment by jbmouret** [comment]
Not sure!

From: http://en.cppreference.com/w/cpp/numeric/random/random_device
"Note that std::random_device may be implemented in terms of a
pseudo-random number engine if a non-deterministic source (e.g. a hardware
device) is not available to the implementation."

**Comment by costashatz** [comment]
> Not sure!
> 
> From: http://en.cppreference.com/w/cpp/numeric/random/random_device
> "Note that std::random_device may be implemented in terms of a
> pseudo-random number engine if a non-deterministic source (e.g. a hardware
> device) is not available to the implementation."

Then we should switch to `Boost`'s random number generators...

**Comment by fedeallocati** [comment]
Maybe use this:
http://www.pcg-random.org/posts/simple-portable-cpp-seed-entropy.html ? It
seems really good and portable.

2016-05-30 6:45 GMT-03:00 Konstantinos Chatzilygeroudis <
notifications@github.com>:

**Comment by costashatz** [comment]
> Maybe use this:
> http://www.pcg-random.org/posts/simple-portable-cpp-seed-entropy.html ? It
> seems really good and portable.

It seems like a good alternative.. @jbmouret what do you think?

**Comment by jbmouret** [comment]
Why not. It seems to be a bit overkill for our humble needs, but if we can directly include the hpp file (and therefore not add a dependency), that might be a possible solution. Otherwise, if std::random_device works well on most OSes, we could live with it.

**Comment by jbmouret** [comment]
Fixed in #114 . I keep it open as a possible improvement.
