### ISSUE TITLE
Compilation of the documentation

### ISSUE THREAD

**Issue by dogoepp** [resibots/limbo#116]
There are many errors and warnings shown during compilation of the docs.
## epstopdf

A number of the errors are reported as:

> sh: 1: epstopdf: not found
> error: Problems running epstopdf. Check your TeX installation!
## Duplicate labels

We also have the following duplicates

> WARNING: duplicate label for keys brochu2010tutorial and brochu2010tutorial
> WARNING: duplicate label for keys matern1960spatial and Rasmussen2006
> WARNING: duplicate label for keys Mockus2013 and stein1999interpolation
> WARNING: duplicate label for keys cully_robots_2015 and matern1960spatial
> WARNING: duplicate label for keys lizotte2007automatic and Mockus2013
## Function declaration parsing

And also, many function definition parsing errors in api.rst:

> /home/dgoepp/Code/limbo/docs/api.rst:221: WARNING: Error when parsing function declaration.
## Other errors

There are also some warnings in api.rst due to title underlines that are too short.

**Comment by dogoepp** [comment]
This issue is to be addressed in the pull request #115.

**Comment by jbmouret** [comment]
On Wed, Jun 1, 2016 at 11:07 AM Dorian Goepp <notifications@github.com>
wrote:

> There are many errors and warnings shown during compilation of the docs.
> epstopdf
>
> A number of the errors are reported as:
>
> sh: 1: epstopdf: not found
> error: Problems running epstopdf. Check your TeX installation!
>
>
Obviously you need to install epstopdf (all of us have by default because
this is part of all the LaTeX installations).


> Duplicate labels
>
> We also have the following duplicates
>
> WARNING: duplicate label for keys brochu2010tutorial and brochu2010tutorial
> WARNING: duplicate label for keys matern1960spatial and Rasmussen2006
> WARNING: duplicate label for keys Mockus2013 and stein1999interpolation
> WARNING: duplicate label for keys cully_robots_2015 and matern1960spatial
> WARNING: duplicate label for keys lizotte2007automatic and Mockus2013
>
>

I kow but I am not sure this our fault.


> Function declaration parsing
>
> And also, many function definition parsing errors in api.rst:
>
> /home/dgoepp/Code/limbo/docs/api.rst:221: WARNING: Error when parsing
> function declaration.
>
>
Again, I think it comes from the Sphinx / Doxygen bridge. I am not sure we
can do anything.


> Other errors
>
> There are also some warnings in api.rst due to title underlines that are
> too short.
>

Who cares?

**Comment by dogoepp** [comment]
> Obviously you need to install epstopdf (all of us have by default because this is part of all the LaTeX installations).

If it is so obvious, I must be stupid.

As of the rest, I hope to remove as many warnings from the compilation as possible, that is why they are listed here.

**Comment by dogoepp** [comment]
Moving from pull request :

# Waf version
Should we write at some places in the docs which version of Waf is currently used for limbo, so that the users can check the documentation ?

**Comment by dogoepp** [comment]
Moving from pull request:

# Version number
Right now, the version number is 0.0 in Sphinx. To be updated ?

**Comment by costashatz** [comment]
> Waf version
> 
> Should we write at some places in the docs which version of Waf is currently used for limbo, so that the users can check the documentation ?

We can. But we should be upgrading at some frequency (e.g. once every 2-3 months).

**Comment by dogoepp** [comment]
Anything new on this front ?

**Comment by dogoepp** [comment]
Anything new on this front ?

**Comment by costashatz** [comment]
What's the status on this one?

**Comment by dogoepp** [comment]
Nothing was done.
