### ISSUE TITLE
review of tutorials/advanced_example.rst

### ISSUE THREAD

**Issue by dogoepp** [resibots/limbo#128]
This is for easier discussion of pull request #115.

# `tutorials/advanced_example.rst`
## around line 7
In the figure, the last "t" of "Target" is trucated.

## around line 14
Why is "Squared exponential covariance function with automatic relevance detection" sorrounded by source code highlight backquotes ? Is there some documentation on this function ?

Before the list, it is written that we will "use the following", but we "optimize the hyperparameters"; not coherent

"Custom output statistics" needs clarification.

## around line 93
What is the role of ``dh_mat`` ? Why not directly using the values of ``rads`` ?

## around line 265
Is it normal that I can't guess what `kernel_squared_exp_ard`, `opt_rprop` and `opt_parallelrepeater` mean ?

## around line 297
> boptimizer.optimize(eval_func<Params>(), aggregator, false);

What is `false` doing ? Is it worth telling the reader about it ?

**Comment by costashatz** [comment]
> around line 7
> 
> In the figure, the last "t" of "Target" is trucated.
> 
> around line 14
> 
> Why is "Squared exponential covariance function with automatic relevance detection" sorrounded by source code highlight backquotes ? Is there some documentation on this function ?
> 
> Before the list, it is written that we will "use the following", but we "optimize the hyperparameters"; not coherent
> 
> "Custom output statistics" needs clarification.
> 
> around line 54
> 
> Is it "function evaluation" or "evaluation function" that we define ?
> 
> around line 93
> 
> What is the role of dh_mat ? Why not directly using the values of rads ?
> 
> around line 137
> 
> Should we link to the section of the documentation where state-based BO is explained ?
> 
> around line 221
> 
> Maybe we can let the user know, what USB and CMAES are and that USB is used to optimise the acquisition function ? Or maybe the user is too clever to need this information ?
> 
> around line 265
> 
> Is it normal that I can't guess what kernel_squared_exp_ard, opt_rprop and opt_parallelrepeater mean ?

We have already discussed them and I think already fixed them.

> What is false doing ? Is it worth telling the reader about it ?

I am doing this right now..

**Comment by dogoepp** [comment]
how do we solve the display of the "target" text in the SVG picture ? (if the matter is not discarded as irrelevant)

**Comment by costashatz** [comment]
> how do we solve the display of the "target" text in the SVG picture ? (if the matter is not discarded as irrelevant)

We do not. In my computer it is appearing correctly, both in Chrome and Firefox. And it is irrelevant really.

**Comment by dogoepp** [comment]
good
