### ISSUE TITLE
review of tutorials/statistics.rst

### ISSUE THREAD

**Issue by dogoepp** [resibots/limbo#129]
This is for easier discussion of pull request #115.

# `tutorials/statistics.rst`
## around line 75
> // [optional] we create a file to write
> //    you can use your own file but remember that this method is called
> //    at each iteration (you need to create it in the constructor)
> this->\_create\_log\_file(bo, "worst_observations.dat");

If manually creating a log file should be done in the constructor, why don't we do the same with ``create_log_file`` ? Even if this method is "safe", meaning that it will attempt to create the file each time, what is the benefit to doing it in this function instead of the constructor ?

> // [optional] we add a header to the file to make it easier to read later
> if (bo.total_iterations() == 0)
>     (\*this->\_log\_file) << "#iteration worst\_observation sample" << std::endl;

same question as above

**Comment by costashatz** [comment]
> Even if this method is "safe", meaning that it will attempt to create the file each time, what is the benefit to doing it in this function instead of the constructor ?

Will we really gain anything? I can do it, if everyone agrees.

**Comment by jbmouret** [comment]
The idea was to avoid requiring a constructor and have shorter / simpler
code. I do not think it is important, therefore both approaches will work
for me.

**Comment by dogoepp** [comment]
OK, less effort option, aborting.
