### ISSUE TITLE
review of guides/limbo_concepts.rst

### ISSUE THREAD

**Issue by dogoepp** [resibots/limbo#131]
This is for easier discussion of pull request #115.

# `guides/limbo_concepts.rst`
## around line 31
I don't get the following exerpt mecanism

> Different solutions exist to deal with missing data. The simplest way consists in redoing the evaluation. This may work, but only if the problem is not deterministic, otherwise the algorithm will be continuously redoing the same, not working, evaluation.

Actually, I finaly understood it, when reaching the end of the paragraph, because couldn't see that the first two paragraphs of this section are not specific to Bayesian Optimisation.

## around line 33
Maybe we can remove ", compatible with Bayesian Optimization," in the second sentence, since it adds little information.

**Comment by costashatz** [comment]
> Maybe we can remove ", compatible with Bayesian Optimization," in the second sentence, since it adds little information.

I think it's good as it is..

But anyway, as I already told you in #115, we are planning on removing blacklists. So we will remove all the documentation of them..

**Closing this issue..**

**Comment by dogoepp** [comment]
you go faster than me. I didn't even have time to check all the things.

My bad. I had done very poorly with  the structure of the review.
