### ISSUE TITLE
review of guides/parameters.rst

### ISSUE THREAD

**Issue by dogoepp** [resibots/limbo#132]
This is for easier discussion of pull request #115.

# `guides/parameters.rst`
## around line 6
Would "Setting parameters in limbo" describe better the content of this guide than "Parameters" ?

**Comment by costashatz** [comment]
> Would "Setting parameters in limbo" describe better the content of this guide than "Parameters" ?

Not really.. I like the "Parameters"..

**Comment by dogoepp** [comment]
don't care
