### ISSUE TITLE
review of api.rst

### ISSUE THREAD

**Issue by dogoepp** [resibots/limbo#133]
This is for easier discussion of pull request #115.

# `api.rst`
## around line 66
> +-- acqui: acquisition functions  
> |-- bayes_opt: bayesian optimizers

Why is there a `+` in front of "acqui" and a `|` for "bayes_opt" ?

**Comment by costashatz** [comment]
> Why is there a + in front of "acqui" and a | for "bayes_opt" ?

By mistake? I am fixing it..

**Comment by costashatz** [comment]
Fixed in b9450ce. **Closing...**
