### ISSUE TITLE
compute BL kernel

### ISSUE THREAD

**Issue by Aneoshun** [resibots/limbo#134]
I add this issue just as a reminder about something that can be improved:
I think we can accelerate the computation of the bl_kernel by combining both the incremental Chol. decomposition and the block-wise inversion (avoid bw-inversion when only one sample is added).

**Comment by jbmouret** [comment]
Hello

My goal is to remove the blacklists and replace them with a constrained
optimization algorithm. As a consequence, I think we should not spend time
on this.

-- JBM

**Comment by costashatz** [comment]
Should we close this issue?

**Comment by Aneoshun** [comment]
Yes, thanks.
