### ISSUE TITLE
LIMBO integration with OpenCV

### ISSUE THREAD

**Issue by JBoggsy** [resibots/limbo#147]
I'm a student working with John Rieffel, and I've been trying to tie an OpenCV-based tracking system into a LIMBO experiment. Unfortunately waf is failing to build because OpenCV is giving numerous undefined reference errors, resulting in a linker error. The OpenCV code works outside of LIMBO when using cmake, and waf configure indicates that it successfully found both the OpenCV includes and libs. 

The tail end of the build step looks like:
`/usr/local/include/opencv2/core/mat.hpp:367: undefined reference to 'cv::Mat::deallocate()'
exp/voltaire/tracker.cpp.1.o:/usr/local/include/opencv2/core/mat.hpp:367: more undefined references to 'cv::Mat::deallocate()' follow
exp/voltaire/tracker.cpp.1.o: In function 'cv::Mat::~Mat()':
/usr/local/include/opencv2/core/mat.hpp:278: undefined reference to 'cv::fastFree(void*)'
collect2: error: ld returned 1 exit status

Waf: Leaving directory '/home/james/Desktop/limbo/build'
Build failed
 -> task in 'tens' failed (exit status 1): 
	{task 139767142594192: cxxprogram main.cpp.1.o,serial.cpp.1.o,tracker.cpp.1.o -> tens}
['/usr/bin/g++', 'exp/voltaire/main.cpp.1.o', 'exp/voltaire/serial.cpp.1.o', 'exp/voltaire/tracker.cpp.1.o', '-o', '/home/james/Desktop/limbo/build/exp/voltaire/tens', '-Wl,-Bstatic', '-Lsrc', '-llimbo', '-Wl,-Bdynamic', '-L/usr/local/lib', '-L/usr/local/lib/', '-L/usr/lib', '-L/opt/intel/tbb/lib', '-L/usr/local/lib', '-L/usr/lib', '-L/usr/local/lib', '-L/usr/lib', '-L/usr/local/lib', '-L/usr/lib', '-lboost_serialization', '-lboost_filesystem', '-lboost_system', '-lboost_unit_test_framework', '-lboost_program_options', '-lboost_graph', '-lboost_thread', '-ltbb', '-lcmaes']
`

The wscript and the opencv.py files for the waf configuration and build are here: [https://gist.github.com/JBoggsy/63d8dab2494a31254f9b119af495a7fe](https://gist.github.com/JBoggsy/63d8dab2494a31254f9b119af495a7fe) if they are useful. 

I can't think of any reason for this to be happening, and was hoping you all had some insight into the matter. I'm not positive it's the LIMBO code, but I can't think of other factors besides it which might be the culprit.

Thanks for the help!

**Comment by costashatz** [comment]
Hello @JBoggsy. First of all thanks for using our code.

In your `opencv.py` you have forgotten to specify to which libraries `OpenCV` should link to. The file should be something like this:

```py
#! /usr/bin/env python
# encoding: utf-8

from waflib.Configure import conf

@conf
def check_opencv(conf):
    # REST OF CODE
      conf.end_msg('got it!')
      # DO NOT FORGET THE FOLLOWING LINE
      conf.env.LIB_OPENCV = ['opencv_core', 'opencv_highgui.so', 'opencv_video', ....]
      conf.env.LIBPATH_OPENCV = libs_check
    # REST OF CODE
      return
```

Also, make sure that you have read the documentation that can be found [here](http://www.resibots.eu/limbo/).

**Comment by JBoggsy** [comment]
Thanks you very much for your help, and your patience! I obviously overlooked that line when I was reading the docs, and I'm sorry for taking up your time.

**Comment by costashatz** [comment]
@JBoggsy no problem! Let us know if you encounter any other issue and/or if the documentation is out of date somewhere..
