### ISSUE TITLE
NoLFOpt called mysteriously

### ISSUE THREAD

**Issue by JBoggsy** [resibots/limbo#151]
When attempting to run the optimization code called by the following two lines, I receive an assertion error **after** the Eval() function has been called the appropriate ten times.

`bayes_opt::BOptimizer<Params, statsfun<stat_t>,m initfun<limbo::init::RandomSampling<Params>>, acquifun<acqui_t>> boptimizer;`
`boptimizer.optimize(Eval());`

The assertion indicates that NoLFOpt should never be called, and a backtrace shows that the model its using is NoLFOpt:

`limbo::model::GP<Params, limbo::kernel::Exp<Params>, limbo::mean::Data<Params>, limbo::model::gp::NoLFOpt<Params> >::optimize_hyperparams
    (this=0x7fffffffe6b8) at /home/james/Desktop/limbo/src/limbo/model/gp.hpp:73`

However, NoLFOpt is not called or even mentioned anywhere in my own code. It's wholly possible I missed something in the documentation, but I've scoured it pretty thoroughly, and can't find anything that has helped.

Thanks for your help and patience!

**Comment by costashatz** [comment]
This assertion comes from these [lines](https://github.com/resibots/limbo/blob/master/src/limbo/bayes_opt/boptimizer.hpp#L126-L128). You have set an `hp_period` (rate at which the hyperparams are optimized) in `boptimizer` bigger than 0 but you are using GP with no hyperparameters optimization. Something that shouldn't happen. So if you do not want to optimize any hyperparameters then set `hp_period` param to -1, or if you want use a GP model that does optimize hyperparams. Check [here](https://github.com/resibots/limbo/tree/master/src/limbo/model/gp) for available hp opt.

> It's wholly possible I missed something in the documentation, but I've scoured it pretty thoroughly, and can't find anything that has helped.

You're right. We do not have anything in the documentation. We should add a hint or something..

**Comment by costashatz** [comment]
@JBoggsy did you fix your issue?

**Comment by JBoggsy** [comment]
Oh yeah, sorry! Setting `hp_period = -1` worked out. No more weird NoLFOpt calls. Thanks a ton for the help!

**Comment by jbmouret** [comment]
We should add this question to the FAQ!

**Comment by costashatz** [comment]
Solved in #154.
