### ISSUE TITLE
Remove gp_multi branch?

### ISSUE THREAD

**Issue by costashatz** [resibots/limbo#152]
Maybe we should remove **gp_multi** branch?

**Comment by jbmouret** [comment]
I think we should.

-- JBM

**Comment by costashatz** [comment]
I think we should also delete `blockwiseinversion`, `init_variance` and `waf_improvements`.

**Comment by jbmouret** [comment]
OK for me but I am not the author of these branches...

**Comment by costashatz** [comment]
@Aneoshun do you agree for `blockwiseinversion`?

@fedeallocati do you agree for `waf_improvements`?

I agree for `init_variance`...

**Comment by Aneoshun** [comment]
@costashatz @jbmouret Yes it's fine to me!

**Comment by fedeallocati** [comment]
Sure! Erase it!

**Comment by costashatz** [comment]
**Done**
