### ISSUE TITLE
BO Reinforcement Learning API 

### ISSUE THREAD

**Issue by fedeallocati** [resibots/limbo#163]
Hi all. I had this idea, and wanted to briefly discuss it and know your opinions.
So far, limbo is a great framework for optimization of functions, and can in a certain way be used to perform RL, but we are always bounded to the main `optimize` loop.
I was thinking that it would be really useful in some cases to have an incremental API, that's driven from the outside of limbo. For example, I imagine the `get_next_sample()` and `add_obs(sample, obs)` methods.
A typical use would be embedding the BO in a bigger controller loop.
Please let me know if you think this is a suitable addition to the library, and also if you have any suggestions!
@Aneoshun @costashatz @jbmouret

**Comment by jbmouret** [comment]
Hi Federico

What would this API give that is not given by the classes on which the BO
algorithms are based on? For instance, you can make a RL algorithm based on
GP by simply call the GP api & the optimization API.

Put differently, the BOptimizer class does not provide that many services.
It mostly agregates the other APIs.

**Comment by jbmouret** [comment]
It's not really an issue of scope. It's more an issue of avoiding
abstractions that have no immediate value.

If we already had several algorithms and we wanted to avoid duplicating the
code, then it would make more sense.

**Comment by costashatz** [comment]
I will mostly agree with @jbmouret on this one. Although, I agree with @fedeallocati that providing some extra functions will make the library a little bit more appealing to new users, I believe that as of now (maybe things will change in the future) we do not really need it.

**Comment by costashatz** [comment]
Closing it until we have something new..
