### ISSUE TITLE
Separate documentation page for latest release

### ISSUE THREAD

**Issue by costashatz** [resibots/limbo#198]
I think we should have a separate automatically generated documentation for the latest release and one for the upstream version (master branch)...

**Comment by jbmouret** [comment]
Agreed. In January.

**Comment by dogoepp** [comment]
Do you mean that you would like that the sphinx documentation to be generated from multiple branches (or tags) ?

**Comment by costashatz** [comment]
> Do you mean that you would like that the sphinx documentation to be generated from multiple branches (or tags) ?

Yes...One website (subdirectory or sub-site) for each... Is it possible?

**Comment by costashatz** [comment]
Any news on that one?

**Comment by dogoepp** [comment]
Work stalled for now due to other tasks that came in the way. Shall I 
come back to it soon ?

**Comment by costashatz** [comment]
> Shall I come back to it soon ?

Not really! I was just wondering where we are with it...

**Comment by costashatz** [comment]
@dogoepp Any progress on this one? With #209 the API of limbo changes a bit than the v1.0 release.

**Comment by dogoepp** [comment]
As said by e-mail I made some progress on this and am waiting for feedback from you guys.

**Comment by costashatz** [comment]
Fixed #229 ...
