### ISSUE TITLE
Linking problem with clang 3.9.1

### ISSUE THREAD

**Issue by ramaroberto** [resibots/limbo#205]
I was trying to compile limbo with clang-3.9.1 in arch (with gcc-6.2.1 it's working fine) and it's throwing this error:

> [23/24] Linking build/src/examples/obs_multi_auto_mean 
> src/examples/obs_multi_auto_mean.cpp.3.o: In function `Matrix<unsigned long>': 
> /usr/include/eigen3/Eigen/src/Core/Matrix.h:296: undefined reference to `fit_eval::dim_out' 
> clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation) 

If I go to "src/examples/obs_multi_auto_mean.cpp:196" and write "Eigen::VectorXd res(2);" instead it links. 

I dug a little bit and I found this: https://pixorblog.wordpress.com/2016/03/09/c-beware-of-constexpr-clang-vs-gcc-standard/, it seems that gcc for some reason it's too permissive, since as it's defined in the standard it shouldn't work. In the comments it says to use Eigen::VectorXd res(decltype(dim_out){}); as a workaround, which makes it compile but it gives an assertion fail of Eigen in running time.

**Comment by jbmouret** [comment]
Do you compile in -O2 or -O3? can you check with ./waf -v?

**Comment by jbmouret** [comment]
(decltype is meaningless here!.. it returns the type of the expression, not its value)

**Comment by ramaroberto** [comment]
Good to know! I'm using the default settings, it's compiling with -O3, this is the relevant output of ./waf -v:

> [ 3/24] Compiling src/examples/obs_multi_auto_mean.cpp
> 20:57:12 runner ['/usr/bin/clang++', '-Wall', '-std=c++11', '-fdiagnostics-color', '-O3', '-g', '-I/home/robert/Projects/Resibots/limbo_new/build/src/examples', '-I/home/robert/Projects/Resibots/limbo_new/src/examples', '-I/home/robert/Projects/Resibots/limbo_new/build/src', '-I/home/robert/Projects/Resibots/limbo_new/src', '-I/home/robert/Projects/Resibots/limbo_new/build', '-I/home/robert/Projects/Resibots/limbo_new', '-I/usr/include', '-I/usr/include/eigen3', '-I/usr/local/include/eigen3', '-I/usr/local/include', '-I/opt/intel/tbb/include', '-DUSE_TBB', '-DUSE_LIBCMAES', '-DUSE_NLOPT', '../src/examples/obs_multi_auto_mean.cpp', '-c', '-o', '/home/robert/Projects/Resibots/limbo_new/build/src/examples/obs_multi_auto_mean.cpp.3.o']

> [23/24] Linking build/src/examples/obs_multi_auto_mean
> 20:57:35 runner ['/usr/bin/clang++', 'src/examples/obs_multi_auto_mean.cpp.3.o', '-o', '/home/robert/Projects/Resibots/limbo_new/build/src/examples/obs_multi_auto_mean', '-Wl,-Bstatic', '-Lsrc', '-llimbo', '-Wl,-Bdynamic', '-L/usr/lib', '-L/usr/local/lib/', '-L/usr/lib', '-L/opt/intel/tbb/lib', '-L/usr/lib/x86_64-linux-gnu/', '-L/usr/local/lib', '-L/usr/lib', '-L/usr/lib/x86_64-linux-gnu/', '-L/usr/local/lib', '-L/usr/lib', '-L/usr/lib/x86_64-linux-gnu/', '-lboost_serialization', '-lboost_filesystem', '-lboost_system', '-lboost_unit_test_framework', '-lboost_program_options', '-lboost_thread', '-ltbb', '-lcmaes', '-lnlopt_cxx']
> src/examples/obs_multi_auto_mean.cpp.3.o: In function `Matrix<unsigned long>':
> /usr/include/eigen3/Eigen/src/Core/Matrix.h:296: undefined reference to `fit_eval::dim_out'
> clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)

Full output is here: http://pastebin.com/sJWk93BA

**Comment by costashatz** [comment]
> it's compiling with -O3

So is it compiling or not? If yes, we should close this issue..

**Comment by costashatz** [comment]
@ramaroberto I am closing this issue.. If you have any objections, you can re-open it..
