### ISSUE TITLE
Split the files into folders

### ISSUE THREAD

**Issue by costashatz** [resibots/limbo#21]
Hey,

I am bringing back on the table @fedeallocati 's idea about splitting the files into folders like Sferes. I think it is a good idea as it will make the folder structure more readable. Also, as we will be adding things (e.g. general optimization framework), it'll be easier to distinguish the functionality each file/folder has. The only drawback will be that we will have some files with very few lines of code, but that's no big deal.

What do you think?

**Comment by fedeallocati** [comment]
+1

**Comment by jbmouret** [comment]
**OK**

**Comment by costashatz** [comment]
Fixed with #26 !
