### ISSUE TITLE
NLOpt with (in)equality constraints

### ISSUE THREAD

**Issue by costashatz** [resibots/limbo#211]
Some algorithms from NLOpt accept (in)equality constraints. We should provide this interface through limbo..

**Comment by trentonbrochill** [comment]
Is there a recommended way to this for now? I’d really be interested in having this capability. The application I am picturing would involve optimizing on the surface of a half hypersphere.

**Comment by costashatz** [comment]
> Is there a recommended way to this for now? I’d really be interested in having this capability. The application I am picturing would involve optimizing on the surface of a half hypersphere.

Thanks for using our library!

Following NLOpt's [tutorial](https://nlopt.readthedocs.io/en/latest/NLopt_Tutorial/), it should be fairly easy to copy (and change name) our [NLOpt wrapper](https://github.com/resibots/limbo/blob/master/src/limbo/opt/nlopt_no_grad.hpp) and create a new one with hard-coded constraints of your preference. If you have any difficulties in this, do not hesitate to contact us..

On a more general note, I thought about it and I have an idea on how to do it more generically. So, I am putting it on my TODO and I will get to it asap (cannot really guarantee how fast it will be :stuck_out_tongue: ).

**Comment by trentonbrochill** [comment]
Wow, you are a very responsive maintainer!
I have only downloaded and built so far, so not much of a user. 

In my case, I'm worried about "hard-coding" the constraints. I was thinking about using this for motion planning in a medium DoF space. I'll be getting new half spheres all the time, then optimizing on them a few steps, but using the same surrogate function globally.
Any ideas for such a weird use case? I would rather re-use your machinery, but maybe I'll actually need to create new optimization for every local problem, but initialize them with a shared gp.

**Comment by costashatz** [comment]
> In my case, I'm worried about "hard-coding" the constraints. I was thinking about using this for motion planning in a medium DoF space. I'll be getting new half spheres all the time, then optimizing on them a few steps, but using the same surrogate function globally.
> Any ideas for such a weird use case? I would rather re-use your machinery, but maybe I'll actually need to create new optimization for every local problem, but initialize them with a shared gp.

In that case, how urgently do you need that feature? I can push it up my TO-DO list...

**Comment by trentonbrochill** [comment]
I looked at the library a little bit more. I think I can hard-code the functional-form of my constraints and then use the dynamic parameter macro to update the parameterization of them. So one user, with a probable work-around, should be lower priority.
