### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by AIAdventures** [resibots/limbo#216]
andrewcz@andrewcz-PORTEGE-Z30t-B ~/limbo $ ./waf configure
Waf: The wscript in '/home/andrewcz/limbo' is unreadable
Traceback (most recent call last):
  File "/home/andrewcz/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Scripting.py", line 100, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/home/andrewcz/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Scripting.py", line 125, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/home/andrewcz/limbo/.waf3-1.8.18-4bb74d2af0d005ad4420ee36f19f050a/waflib/Context.py", line 354, in load_module
    try:exec(compile(code,path,'exec'),module.__dict__)
  File "/home/andrewcz/limbo/wscript", line 134
    print 'CXXFLAGS:', conf.env['CXXFLAGS']
                    ^
SyntaxError: Missing parentheses in call to 'print'
andrewcz@andrewcz-PORTEGE-Z30t-B ~/limbo $ 

was getting the above error when trying to install.
Many thanks,
BEst,
Andrew

**Comment by costashatz** [comment]
Hello Andrew,

Thanks for using our library. What version of python are you using (try typing `python -V` in your cmd)? It seems that you are using Python3, but our `wscript` files (something like `CMakeLists.txt`) are written with Python2.7 in mind.

Can you try switching to python2.7 and trying again?

Also, can you let me know what is your OS and which version?

Thanks..!

**Comment by AIAdventures** [comment]
sincere apologies you are correct!
Not sure how to switch my python

**Comment by jbmouret** [comment]
You can probably do 

`python2.7 ./waf`

(or the path to your python 2.7 / 2.6).

**Comment by AIAdventures** [comment]
Looks like it's working now 😃.
Will try the examples 😃
Cheers Andrew

On 19 May 2017 10:43 pm, "JB Mouret" <notifications@github.com> wrote:

You can probably do

python2.7 ./waf

(or the path to your python 2.7 / 2.6).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/resibots/limbo/issues/216#issuecomment-302692601>, or mute
the thread

**Comment by costashatz** [comment]
Let us know if you have any other issues...!

**Comment by costashatz** [comment]
Or comments.. :smile:

**Comment by AIAdventures** [comment]
Hahah ok will do.
Looks like the Start of awesome library 😃.
Many thanks,
Best,
Andrew

**Comment by costashatz** [comment]
@AIAdventures can you check if #222 solves your issue above? Thanks!
