### ISSUE TITLE
Make our wscript / waf compatible with python3

### ISSUE THREAD

**Issue by jbmouret** [resibots/limbo#217]

**Comment by costashatz** [comment]
As far as I can understand from waf's README, they support python3 and thus we should make our wscript files compatible with python3:

> HOW TO CREATE THE WAF SCRIPT
>
>Python >= 2.6 is required to generate the waf script, and the resulting file can then run on Python 2.5. Just execute:
>
>    `$ ./waf-light configure build`
>Or, if you have several python versions installed:
>
>    `$ python3 ./waf-light configure build`
