### ISSUE TITLE
Cleaning code tool breaks a macro

### ISSUE THREAD

**Issue by fedeallocati** [resibots/limbo#22]
When running the tool over the macros file, it does the following:
Lines 25, 26 and 27 before the running:
```
#define __VA_ARG_N( \ 
         _1, _2, _3, _4, _5, _6, _7, _8, _9,_10, \ 
        _11,_12,_13,_14,_15,_16,_17,_18,_19,_20, \ 
```
Lines 25, 26 and 27 after the running:
```
#define __VA_ARG_N(
         \ 
         _1, _2, _3, _4, _5, _6, _7, _8, _9,_10, \ 
```

This naturally prevents not only the macro from working, but also the code from compiling

**Comment by costashatz** [comment]
For a quick fix, you can use `clang-format off` and `clang-format on`.

I will check if there's a better solution.

**Comment by fedeallocati** [comment]
This happened because there was a space after the '\'. Closing it now
