### ISSUE TITLE
Minor errors and inaccuracies in documentation

### ISSUE THREAD

**Issue by alexendy** [resibots/limbo#226]
Hi,

I just wanted to signal two minor issues in the documentation:
- The expression of the squared exponential kernel [in the introduction to BO guide](http://www.resibots.eu/limbo/guides/bo.html#optimizing-the-hyper-parameters-of-a-gaussian-process) is missing a minus sign in the exponential
- The expression of the same squared exponential kernel [in the API reference](http://www.resibots.eu/limbo/api.html#_CPPv2N5limbo6kernel3ExpE) has the minus sign, but is missing the 1/2 factor.

Best,

Alex

**Comment by costashatz** [comment]
Hey,

Thanks for the feedback! Fixed the issues #227!
