### ISSUE TITLE
Combination of all posible settings for BOptimizer

### ISSUE THREAD

**Issue by fedeallocati** [resibots/limbo#24]
I have good news. I made a python script that generate all possible combinations of kernel, mean, model, acquisition, init, and inner optimization, which, (skiping things that are no compatible, for example GPAuto with a kernel different than SquaredExpARD), gives more than 600 combinations). After some small corrections I made on the branch all_combinations_test_and_fixes, all the combinations compile.
So, why this issue? Well, it took around 1 hour and 15 minutes to compile everything (even after separating each combination in a different file, to compile in parallel), so it's infeasible to run this after each change in any of the parts of the system. 
I think maybe we should make a manual test, where we make sure to use each class at least once, but not covering all combinations. Any other ideas are welcome!

**Comment by jbmouret** [comment]
On 21 Oct 2015, at 20:47, Federico Allocati <notifications@github.com> wrote:

> I have good news. I made a python script that generate all possible combinations of kernel, mean, model, acquisition, init, and inner optimization, which, (skiping things that are no compatible, for example GPAuto with a kernel different than SquaredExpARD), gives more than 600 combinations). After some small corrections I made on the branch all_combinations_test_and_fixes, all the combinations compile.
> So, why this issue? Well, it took around 1 hour and 15 minutes to compile everything (even after separating each combination in a different file, to compile in parallel), so it's infeasible to run this after each change in any of the parts of the system. 
> I think maybe we should make a manual test, where we make sure to use each class at least once, but not covering all combinations. Any other ideas are welcome!

And how much time to run all the tests?

1:15 is not that much but of course we do not want to run this 10 times a day. 

We have a similar issue with the �bo_functions� test, that is quite extensive but too slow to be used as unit tests. It will be the same when we will compare our code to BayesOpt.

We could have two levels of tests: classic unit tests that we run often, and �extensive tests�, that we run less often (e.g. once a week on the cluster ?).

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by fedeallocati** [comment]
I haven't tried them because I was already at home when I compiled them, but also because they aren't exactly tests. I enforced the calling of some templated functions just to make sure that they where compiled, but there isn't any BOOST_CHECK or anything.
I'm sure that MeanArchive won't work, first because I don't have any archive, and second because it's targeted to the hexapod experiment, like it expects the samples to have 6 dimensions. We could make this work with any sample and observation size.
In the way it's coded now, I think it tries to recompile this every time, so maybe we should move this kind of test to a waf function different than build.
I could measure how much time it takes to compile this on the cluster, and if it is not that much, maybe we can add something like a github hook, to compile it everytime something gets pushed, or with every pull request(don't know if this is posible) or something like that.

**Comment by costashatz** [comment]
I think I agree with @jbmouret . It's best if we use `waf` to specify which tests we want it to compile and separate the tests into `unit tests` and `extensive tests`. The former should be compiled & run every time we make a change to check that we didn't break something big and the latter should be compiled & run every once in a while to be sure that we didn't break anything at all.

**Comment by costashatz** [comment]
Solved with #25 !
