### ISSUE TITLE
the empirical idea about the performance of Bayesian optimization for high dimension (parameters).

### ISSUE THREAD

**Issue by langongjin** [resibots/limbo#264]
I am going to test high dimension (20~40 parameters, or more) objective function. 
Do you have some empirical idea to me how is BO learning process for high dimension? 
From my review about the Bayesian optimization, some research present it is not very good learning for high dimension and propose some improving methods for high dimension. 
Can you recommend me some papers about how is the learning tendency of Bayesian optimization for different dimension?

**Comment by jbmouret** [comment]
In our experience, BO does not work well with more than ~10 parameters. To scale up, we often use priors:
- https://arxiv.org/abs/1709.06919 
- https://arxiv.org/abs/1407.3501

**Comment by langongjin** [comment]
what do you mean "not work well"? low convergence speed, or can not find the optimal, both? or something else? Thanks!

**Comment by costashatz** [comment]
Slow convergence silently implies that the algorithm cannot really find the optimal (as it would need many many samples to find it). Of course, it depends on the structure of the objective function; if it is too easy or too hard.. But usually, as @jbmouret, for more than ~10 parameters BO does not easily converged and most of the times struggles to find the optimal..

**Comment by langongjin** [comment]
okay, Thanks!
