### ISSUE TITLE
Avoid duplication of samples and observations

### ISSUE THREAD

**Issue by fedeallocati** [resibots/limbo#28]
We discussed this on the first meeting. Each time GP.compute(...) is called, it makes a copy of the samples and observations. We could try to avoid this holding them in only one place.
Just leaving this issue so sometime we try it.

**Comment by costashatz** [comment]
Now that we are making a copy of the GP at every `utility` call, we should put this enhancement higher in our priorities. @fedeallocati can you do it?

**Comment by fedeallocati** [comment]
I've got lots of things in my TODO list, but after changing the main loop and the improvement of the stats, this can be my next task.
