### ISSUE TITLE
The problems of "init_randomsampling" in the nature tasks.

### ISSUE THREAD

**Issue by langongjin** [resibots/limbo#282]
hi, 
Could the value of "samples" be 1 in the function "init_randomsampling" ? as following:
`    struct init_randomsampling : public defaults::init_randomsampling {
        BO_PARAM(int, samples, 1);
    };
`
For default parameter "samples = 10", it is easy to random sampling 10 times in the task of searching the optimal of the function. But my task foucs on the robot movement. Therefore, it need to test robot moving ten times if the "samples" is 10. This is not I want. Thus, I want to set the "samples" to be 1.

Notice: In my understanding, The parameter "samples" only work in the begining (we could say first generation). Therefore, it is also not good to compare with another algorithms if the "samples = 10". I tested "samples = 10" and "samples = 1" for searching the optimal of a function.

"samples = 10"
![11535119763_ pic](https://user-images.githubusercontent.com/13703853/44590788-4817a700-a7bc-11e8-97a8-a252a51407b0.jpg)

"samples = 1"
![21535119887_ pic_hd](https://user-images.githubusercontent.com/13703853/44590842-65e50c00-a7bc-11e8-85c3-fa4d6a80b29c.jpg)

It is make sense that the learning of "samples = 10" is much faster than "samples = 1". But in my robot movement task, the "samples = 10" will take the same computation as 10 generations. This is why I want to set "samples = 1".

But the thing is, it need more than 3 initial samples for the standard deviation in Bayesian optimization. Therefore, I want to know how I can figure out this problems. 

Thanks!

**Comment by Aneoshun** [comment]
Hi, 

The "samples" parameter can take any value, even 0. 
These random samples are only generated at the beginning, as you said. They are used to initialize the model (GP) with some data without any prior knowledge. Once the model is initialized with the data, it can be used to drive the exploration and to select the next samples. 

If you want to compare algorithms using different numbers of initial samples, I suggest you to base your analysis on an "evaluation budget". For instance, each algorithm has a budget of 100 evaluations. If you use 10 random initial samples, then you can only use 90 generations. If you use 1 initial sample, then you can use 99 generations. 

Finally, you do not need more than 3 initial samples for the standard deviation in BO. As I said, it can also work with 0 initial samples (give it a try!). The initial samples are mainly here to rapidly get a rough estimate of the optimized function. A random, and well spread distribution of initial samples will give a reasonable initial estimate, while without initial samples, you might be more likely to end up into a local optimum. 

I hope you will find these comments useful. Let us know if you have further questions.

**Comment by langongjin** [comment]
hi, @Aneoshun your answer is definitely perfect for my question. Thank you very much!
