### ISSUE TITLE
Why this Bayesian optimization benchmarks

### ISSUE THREAD

**Issue by langongjin** [resibots/limbo#288]
hi, 
A small question: Why we used the functions from https://www.sfu.ca/~ssurjano/optimization.html as the benchmarks to compare the performance of Limbo against BayesOpt? In general, we use the BBOB https://github.com/numbbo/coco as the benchmarks. Because we can not compare the performance if the benchmark is not fair. Sometimes, the different algorithms/libraries have different performances on the different benchmark.

**Comment by jbmouret** [comment]
We used a few functions from the Bayesopt examples and a few additional classic ones from the literature. Our current set is not nearly as extensive as the set of COCO.

It might be useful to try the set of function used COCO in the future or try COCO directly, although my experience with COCO & C++ (especially multithreaded C++) has not been very good so far (as COCO is far from being thread safe).

**Comment by langongjin** [comment]
Nice answer for me. Thank you!
