### ISSUE TITLE
Undefined Reference to OpenMP functions

### ISSUE THREAD

**Issue by Giuseppe5** [resibots/limbo#293]
Hi everyone.

I'm having troubles in using Eigen+OpenMP with Limbo. In particular after doing `./waf configure`, I can see that the "-fopenmp" flag is added, but when doing `./waf build`, I get:

> /usr/local/include/eigen3/Eigen/src/Core/products/Parallelizer.h:123: undefined reference to `omp_get_num_threads'
/usr/local/include/eigen3/Eigen/src/Core/products/Parallelizer.h:34: undefined reference to `omp_get_max_threads'
/usr/local/include/eigen3/Eigen/src/Core/products/Parallelizer.h:134: undefined reference to `GOMP_parallel'
/usr/local/include/eigen3/Eigen/src/Core/products/Parallelizer.h:34: undefined reference to `omp_get_max_threads'

I have tried a simple script where I tested some of those function including `<openmp.h>`, compiling with -fopenmp and checked if EIGEN_HAS_OPENMP is defined, and everything works fine.

I'm on Ubuntu 18.04, g++ version is 7.3.0

**Comment by costashatz** [comment]
Hello @Giuseppe5 ,

Do you have TBB installed and enabled?

**Comment by Giuseppe5** [comment]
Yes, it looks like it's present (according to the output to `sudo apt-get install libtbb-dev`) and working (with a simple script that executes  `tbb::task_scheduler_init init;`)

**Comment by costashatz** [comment]
> Yes, it looks like it's present (according to the output to `sudo apt-get install libtbb-dev`) and working (with a simple script that executes `tbb::task_scheduler_init init;`)

Can you disable TBB and try again?

**Comment by Giuseppe5** [comment]
How exactly?
I tried commenting in the "main" wscript the two lines associated to tbb (`conf.load('tbb)` and `conf,check_tbb()`) but I get the same error.

**Comment by costashatz** [comment]
Inside limbo root directory:

```bash
./waf clean
./waf configure --tbb=/tmp/
./waf
```

**Comment by Giuseppe5** [comment]
I tried as you said but nothing changes

**Comment by costashatz** [comment]
> I tried as you said but nothing changes

OK. So there's no interference between TBB and OpenMP..

Can you give me the wscript you are using for your project?

**Comment by Giuseppe5** [comment]
Here it is. 
However the problem is that I get that error even with no experiments, when trying to build the limbo examples and benchmarks.
The only way to go through and build everything, including my own experiments, is to comment in the "main" wscript the line for the inclusion of -fopenmp flag.
[wscript.zip](https://github.com/resibots/limbo/files/2876397/wscript.zip)

**Comment by costashatz** [comment]
I think I found a way to fix this. I will try to make a PR as soon as possible.

**Comment by Giuseppe5** [comment]
Nice, thanks :)
Keep me updated!

**Comment by Giuseppe5** [comment]
It worked perfectly!

Thank you very much!!
