### ISSUE TITLE
Limbo without boost

### ISSUE THREAD

**Issue by bvdmitri** [resibots/limbo#296]
Is it possible to use limbo project without boost? I just checked almost all of your documentation and realized that this library fits my needs. But I only need a very little part of it related to GP routines and acquisition functions implementations.

**Comment by costashatz** [comment]
Hello @bvdmitri,

Thanks for using our library. The whole library is header only and thus you can take only the parts that you want and include them in your project. 

The only issue that you would have is that you would need to edit a bit the `macros.hpp` to remove the boost dependency.

Let me know if you need any help. 

Sorry for the late reply..

**Comment by bvdmitri** [comment]
Thank you for reply.
I decided to you library as is, with boost as a dependency. May be with extra time I will try to edit `macros.hpp` as you suggested.
I think it can be closed.
