### ISSUE TITLE
how to run gp for multi-dimension input 

### ISSUE THREAD

**Issue by MUXIANGRU** [resibots/limbo#308]
Hi,
   I want to use limbo to do something similar to curve fitting.It means that two dimensions of input need to be given(such as x,y coordinates) to predict the curve(z coordinates).How can I achieve this goal by using this tool?

Thanks!

**Comment by costashatz** [comment]
We have a few tutorials and I think they will help you understand what you need to do: http://www.resibots.eu/limbo/tutorials/index.html
