### ISSUE TITLE
Can't find MSCV 14 when using waf for Visual Studio 2017

### ISSUE THREAD

**Issue by bfrancois42** [resibots/limbo#309]
Hi,

I try to compile limbo using waf as described in the documentation.

But I can't figure out how to give MSCV 14 to waf (it should be this version of Windows c++ toolset according to [https://devblogs.microsoft.com/cppblog/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2017/](https://devblogs.microsoft.com/cppblog/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2017/)) .

When the soft looks for 'CL' program, it doesn't reach Visual studio 15 folder (equivalent to VS2017) but stops at Visual Studio 12. My output is in the attached text file.

Has anyone successed to do that ? I tryed with waf 2.0 also and I'm still struggling with it.
[Output.txt](https://github.com/resibots/limbo/files/5590812/Output.txt)

**Comment by costashatz** [comment]
@bfrancois42 thanks for using our library!

We have never used limbo in Windows. Even if you manage to integrate waf with MS Visual Studio, the waf_tools for detection are tailored for Linux/Mac: you would have to either adapt the configuration files or add options when configuring.

I will leave this open in case someone finds a solution for this..

**Comment by jbmouret** [comment]
I think we never tried Limbo on Windows.

I would suggest to not use waf: just use the limbo headers in msvc (limbo is header-only for almost everything).
