### ISSUE TITLE
Optimize different types of parameters

### ISSUE THREAD

**Issue by bfrancois42** [resibots/limbo#310]
Hi,

I managed to install and use Limbo for basic function optimization problems. Is there a way to mix different types of parameters in my experiment ? Like floating numbers, integers and categorical types. It could help me for my different Machine Learning applications.

Regards,
Brice

**Comment by jbmouret** [comment]
Not really: Gaussian processes are really only good for float numbers and we used Eigen::VectorXd everywhere (so, double). 

In general, mixing integers, float, and categorical types is very difficult to do cleanly....
