### ISSUE TITLE
Optimization tolerances

### ISSUE THREAD

**Issue by kirilllzaitsev** [resibots/limbo#316]
Hi, I'm using NLoptNoGrad's fun_tolerance and xrel_tolerance to stop optimization when the process has converged.
From LIMBO docs:
```

limbo::defaults::opt_nloptnograd::BO_PARAM(double, fun_tolerance, - 1)

tolerance for convergence: stop when an optimization step (or an estimate of the optimum) changes the objective function value by less than tol multiplied by the absolute value of the function value. IGNORED if negative
```

I expect these to work accordingly:
```

        BO_PARAM(double, xrel_tolerance, 1e-1);
        
        BO_PARAM(double, fun_tolerance, 1e-1);
```

However, I get the following gp_acquisitions.dat:
```

#iteration mu sigma acquisition
0 43.3979 0.557294 0.297819
1 44.2364 0.0328536 0.838567
2 44.9443 2.0007e-05 0.00178443
3 44.9444 1.50042e-05 0.00154532
4 44.9444 1.33363e-05 0.00145689
5 44.9444 1.25023e-05 0.0014106
6 44.9444 1.20019e-05 0.00138208
7 44.9444 1.16682e-05 0.00136274
8 44.9444 1.14299e-05 0.00134875
9 44.9444 1.12512e-05 0.00133816
10 44.9444 1.11122e-05 0.00132987
11 44.9444 1.1001e-05 0.0013232
12 44.9444 1.091e-05 0.00131772
13 44.9444 1.08341e-05 0.00131313
14 44.9444 1.077e-05 0.00130923
15 44.9444 1.0715e-05 0.00130589
16 44.9444 1.06673e-05 0.00130298
17 44.9444 1.06256e-05 0.00130043
18 44.9444 1.05888e-05 0.00129818
19 44.9444 1.05561e-05 0.00129617
20 44.9444 1.05268e-05 0.00129437
21 44.9444 1.05005e-05 0.00129275
22 44.9444 1.04767e-05 0.00129128
23 44.9444 1.0455e-05 0.00128995
24 44.9444 1.04352e-05 0.00128873
25 44.9444 1.04171e-05 0.00128761
26 44.9444 1.04004e-05 0.00128657
27 44.9444 1.0385e-05 0.00128562
28 44.9444 1.03707e-05 0.00128474
29 44.9444 1.03575e-05 0.00128392
30 44.9444 1.03452e-05 0.00128315
31 44.9444 1.03337e-05 0.00128244
32 44.9444 1.03229e-05 0.00128177
33 44.9444 1.03128e-05 0.00128115
34 44.9444 1.03033e-05 0.00128056
```

where acquisitions differ by less than 1e-1*x, but iteration goes on. Having read https://stackoverflow.com/questions/34755612/unexpected-behaviour-of-ftol-abs-and-ftol-rel-in-nlopt, not sure if I can use the tolerances at all.

**Comment by costashatz** [comment]
**limbo** is just setting NLOpt's termination conditions: see [here](https://nlopt.readthedocs.io/en/latest/NLopt_Introduction/#termination-conditions) for a detailed description. In my experience, those stopping criteria were working okayish.

Some crucial parts:

- `fun_tolerance` -> `Instead most algorithms implement these as a tolerance for the decrease Δf in the function value from one iteration to next (or something similar to that): the algorithm stops if |Δf|/|f| is less than ftol_rel, or |Δf| is less than ftol_abs.`
- `xrel_tolerance` -> `so in practice Δx is usually some measure of how much x changes by from one iteration to the next, or the diameter of a search region, or something like that. Then the algorithm stops when either |Δxi| < xtol_absi or when |Δxi|/|xi| < xtol_rel. However, there is some variation in how the different algorithms implement x tolerance tests; for example, some of them check instead whether |Δx|/|x| < xtol_rel, where |•| is some norm`

Also you should keep in mind (as they say in the docs) that each algorithm implements those termination conditions differently and some of them might not even support them.
