### ISSUE TITLE
Issue with #pragma omp parallel

### ISSUE THREAD

**Issue by kirilllzaitsev** [resibots/limbo#317]
I'm trying to parallelize LIMBO optimization over Eigen's data using OpenMP.
The following chunk of code for a single thread runs just fine:

    std::vector<Eigen::Matrix3d> datas;
    data1 << 1, 1, 1, 1, 1, 1, 1, 1, 1;
    data2 << 1, 1, 1, 1, 1, 1, 1, 1, 1;
    datas.push_back(data1);
    datas.push_back(data2);
    #pragma omp parallel num_threads(1)
    {
    #pragma omp for
        for (auto data : datas)
        {
            boptimizer.optimize(eval_func<Params>(data));
        }
    }

However, using **num_threads(2)** in the same code leads to an error:
```

0 new point: 0 new point: 0.9444440.944444 value:  value: 36.5 best:36.5 best:43.8481
43.8481
updates: /usr/include/eigen3/Eigen/src/Core/Product.h:96: Eigen::Product<Lhs, Rhs, Option>::Product(const Lhs&, const Rhs&) [with _Lhs = Eigen::Transpose<const Eigen::Matrix<double, -1, 1> >; _Rhs = Eigen::Matrix<double, -1, -1>; int Option = 0; Eigen::Product<Lhs, Rhs, Option>::Lhs = Eigen::Transpose<const Eigen::Matrix<double, -1, 1> >; Eigen::Product<Lhs, Rhs, Option>::Rhs = Eigen::Matrix<double, -1, -1>]: Assertion `lhs.cols() == rhs.rows() && "invalid matrix product" && "if you wanted a coeff-wise or a dot product use the respective explicit functions"' failed.
Aborted
make: *** [Makefile:2: run] Error 134
```

Following steps from [this issue](https://github.com/resibots/limbo/issues/293) didn't help. Wondering if this is a known issue?

**Comment by costashatz** [comment]
The code you provide showcases that you haven't understood how to use `limbo`. I am actually surprised that this code compiles! I am curious what the code gives using 1 thread. What is being optimized here? Can you share the whole code?

I suggest that you spend some time to read the documentation of the library: [here](http://www.resibots.eu/limbo/).

Start from the tutorials. Reading the [BasicExample](http://www.resibots.eu/limbo/tutorials/basic_example.html) should give you a quite good idea on how to use limbo. Basically you cannot pass matrices to the `eval_func`, and `boptimizer.optimize` **runs a FULL optimization** and not just one iteration. The idea is that you create an `Eval` struct (you can change the name) that defines how to call your objective function. Here's the one from basic example where we want to optimize a simple 1D function:

```cpp
struct Eval {
    // number of input dimension (x.size())
    BO_PARAM(size_t, dim_in, 1);
    // number of dimensions of the result (res.size())
    BO_PARAM(size_t, dim_out, 1);

    // the function to be optimized
    Eigen::VectorXd operator()(const Eigen::VectorXd& x) const
    {
        double y = -((5 * x(0) - 2.5) * (5 * x(0) - 2.5)) + 5;
        // we return a 1-dimensional vector
        return tools::make_vector(y);
    }
};
```

Lastly, parallelizing evaluations of boptimizer do not make sense at the current implementation of limbo. At each iteration, BOptimizer evaluates exactly ONE parameter vector (the result of the optimization of the acquisition function), so there would not be any usecase for parallelization there. There exists methods that the optimization of the acquisition function outputs several points to evaluate but this is not implemented in limbo yet.

Hope this was helpful!

**Comment by kirilllzaitsev** [comment]
Hold on. In my case, I'm trying to find best pair of params _(a, b),_ where _a_ is an integer with two values, and _b_ is in [0, 1]. This I translate into two independent, hence parallel, limbo optimizations just over _b_ for each value of _a_. 

The code for eval_func is the following:

```
int count = 0;

double _eval_func(const double alpha, const Eigen::MatrixXd &data) {
    auto tmp = data.array().square();
    auto score = 5.0 - alpha * tmp;
    std::cout << "calling _eval_func " << count << std::endl;
    count++;
    return score.sum();
}

template<typename Params>
struct eval_func {
    BO_PARAM(size_t, dim_in, 1);

    BO_PARAM(size_t, dim_out, 1);
    Eigen::MatrixXd data;
    std::function<double(double, const Eigen::MatrixXd &)> _eval_func;

    eval_func() {}

    explicit eval_func(const Eigen::MatrixXd &data) {
        this->data = data;
    }

    Eigen::VectorXd operator()(const Eigen::VectorXd &x) const {
        double alpha = x(0);

        return tools::make_vector(_eval_func(alpha, data));
    }
};
```

**Comment by costashatz** [comment]
First, I do not think that you need this: `std::function<double(double, const Eigen::MatrixXd &)> _eval_func;`.

Afterwards, try the following:

```cpp
std::vector<Eigen::Matrix3d> datas;
data1 << 1, 1, 1, 1, 1, 1, 1, 1, 1;
data2 << 1, 1, 1, 1, 1, 1, 1, 1, 1;
datas.push_back(data1);
datas.push_back(data2);
// set the number of threads you want
#pragma omp parallel num_threads(2)
{
#pragma omp for
    for (auto data : datas)
    {
        limbo::bayes_opt::BOptimizer<...> boptimizer;
        boptimizer.optimize(eval_func<Params>(data));
    }
}
```

In essence, the way things are implemented in limbo, you cannot use the same `BOptimizer` object in two threads at the same time. Creating a new object should be quite fast..

Let me know if it works...

**Comment by kirilllzaitsev** [comment]
Thank you, it works
