### ISSUE TITLE
Question: Is multiobjective bayesian optimization code in "experimental" safe to use?

### ISSUE THREAD

**Issue by 123epsilon** [resibots/limbo#319]
Hi, I am interested in implementing multiobjective bayesian optimization with limbo and I saw that there are experimental implementations of a multiobjective bayesian optimizer as well as implementations of acquisition functions such as EHVI, are these safe to use or should I attempt to implement them myself?

**Comment by jbmouret** [comment]
The EHVI computation should work well (it's not made by us). Overall, these functions should be 'safe' to use but they might need some tuning / polishing.

**Comment by 123epsilon** [comment]
Great, thank you.
