### ISSUE TITLE
Manually set initial values to Bayesian Optimization?

### ISSUE THREAD

**Issue by jussihi** [resibots/limbo#322]
Is there a way to manually give at least some of the initial values for the BO?

Currently I'm using `struct init_randomsampling` in my `Params` struct, but as its name implies, the samples are randomly drawn.

Let's say I have made a good guess for the solution of my problem and I would like to include this guess to my init samples. How could I do this?

**Comment by costashatz** [comment]
You just need to create a new initialization structure. You can take the `RandomSampling` (see [here](https://github.com/resibots/limbo/blob/master/src/limbo/init/random_sampling.hpp)) as an example and create your new one. Then make sure to pass the new initialization scheme to the `BOptimizer`: you can do this by `bayes_opt::BOptimizer<..., init_fun<MyNewInit>,...>` when creating your `BOptimizer` object.

**Comment by jussihi** [comment]
Thank you @costashatz . I was able to do it with your instructions. Small note, the right name for the initialization function in `BOptimizer`'s constructor is `initfun`, not `init_fun`.

Since LIMBO is licensed under CECILL-C which is somewhat similar to LGPL and obligates me to publish any changes/improvements made to the library itself, do you want me to publish the changes I've made to achieve my initial requirement (setting manual initial values / good guess to `BOptimizer`). If so, how would you prefer me to publish them?

**Comment by jussihi** [comment]
I will also close this issue, since I got my question answered long ago. Too bad I was not able to contribute since I never received any instructions for code review, etc.

**Comment by costashatz** [comment]
> Too bad I was not able to contribute since I never received any instructions for code review, etc.

Hello @jussihi. Sorry for the very late reply. You are welcome to contribute any code you wish.

Feel free to make a PR and we will review it.
