### ISSUE TITLE
Review main optimizer loop

### ISSUE THREAD

**Issue by fedeallocati** [resibots/limbo#36]
As of now our main loop in the boptimizer is:
```
init()

if !observations.empty()
    model.compute()
end if 

while samples.empty() or !stop:
    new_sample = max arg (acquisition)
    new_obs = eval(new_sample)
    samples.add(new_sample)
    observations.add(new_obs)
    model.compute()
    update_stats()
end while
```
We where wondering with JB if this was the best way to perform it. An issue that for example raises is that the stats are updated after the model, so if you wanted to register something about the model before the updating (for example the variance of the new_sample, which only makes sense before the update, because after it should be really low), you can't.
A different idea could be:
```
init()

while samples.empty() or !stop:

    if !observations.empty()
        model.compute()
    end if

    new_sample = max arg (acquisition)
    new_obs = eval(new_sample)
    samples.add(new_sample)
    observations.add(new_obs)
    update_stats()
end while

if !observations.empty()
        model.compute()
end if
```
I'm opening this issue to discuss what we all consider the best option, and leave a record of our choice.

**Comment by costashatz** [comment]
So, what should we do at the end? Should we add `stat slots`? Or should we make use of the `dump_period` as in mentioned in #37? Ideas?

**Comment by fedeallocati** [comment]
After thinking heavily about this, I really think that just having the second loop, will suit all our needs. Maybe just add a slot for update stats after the computing of the model, although I don't see any use for it besides checking that the sigma for the last sampled point diminished.
In any case, if you want to add that slot, I vote for adding it as a template parameter of the BOptimizer. Since we are using optimal named template parameters, just the ones that need that slot can use it, and we don't get the stats dirty.

**Comment by costashatz** [comment]
This was handled in #44 !
