### ISSUE TITLE
Improvement on Stats

### ISSUE THREAD

**Issue by fedeallocati** [resibots/limbo#37]
I wanted to propose some improvements on the Stats:
- Rename Acquisitions to something more significant. Acquisitions sounds like the value of the acquisition function. Maybe separate it in two: Samples and Observations.
- We agreed with JB that it's better to do the output in a standard format: values separated by spaces. To give an indication to a reader of the file of which values the columns represent, we think that we can include in the first line of the file a comment (starting the line with a '#') and put the columns headers there.
- Start using the dump_period parameter, which is not used, or remove it if we think we will always output statistics at every iteration
- We should add more stats! The first one I can think of is BestObservation. Also I saw on Antoine's code HyperparametersStat which outputs the GP kernel's and mean's hyperparameters at each step.

Proposals, critics, etc are welcome!

**Comment by costashatz** [comment]
> Rename Acquisitions to something more significant. Acquisitions sounds like the value of the acquisition function. Maybe separate it in two: Samples and Observations.

I think I like the separation.

> We agreed with JB that it's better to do the output in a standard format: values separated by spaces. To give an indication to a reader of the file of which values the columns represent, we think that we can include in the first line of the file a comment (starting the line with a '#') and put the columns headers there.

It's a good idea.

> Start using the dump_period parameter, which is not used, or remove it if we think we will always output statistics at every iteration

The pros of `dump_period` is that we can precisely handle when to output stats, but do we really need it? What can change that cannot be captured in the iteration loop? It makes senses to use this kind of functionality if we add stats to the models, optimizers etc. It could be a good addition, but I don't know if it should be our priority.

> We should add more stats! The first one I can think of is BestObservation. Also I saw on Antoine's code HyperparametersStat which outputs the GP kernel's and mean's hyperparameters at each step.

+1 for Hyperparameters and BestObservation.

**Comment by jbmouret** [comment]
> The pros of dump_period is that we can precisely handle when to output stats, but do we really need it? What can change that cannot be captured in the iteration loop? It makes senses to use this kind of functionality if we add stats to the models, optimizers etc. It could be a good addition, but I don't know if it should be our priority.

We use this a lot in sferes to avoid dumping too much data (it easily takes Tb of data). This might not be that useful in limbo, that do not write nearly as much data.

**Comment by jbmouret** [comment]
> We should add more stats! The first one I can think of is BestObservation. Also I saw on Antoine's code HyperparametersStat which outputs the GP kernel's and mean's hyperparameters at each step.
> +1 for Hyperparameters and BestObservation.

OK for this, of course.

**Comment by jbmouret** [comment]
> Rename Acquisitions to something more significant. Acquisitions sounds like the value of the acquisition function. Maybe separate it in two: Samples and Observations.
> I think I like the separation.

OK for this.

**Comment by costashatz** [comment]
This is done by #45 !
