### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by costashatz** [resibots/limbo#41]
What coding will we adopt for Limbo at last? Using sferes2 naming conventions is one option. I list them here:
1. Names representing classes must be in camel case: e.g. MyClass
2. Variable and method names must be in lower case, using underscores to separate words: my_variable, my_method()
3. Names of protected and private members must start with an underscore: _my_private_member, _my_private_method()
4. File names must be in lower case, using underscores to separate words. A file which contains a class MyClass should be put in a file my_class.hpp
5. File structure mirrors namespace structure. For instance gen::MyClass is in the file gen/my_class.hpp
6. Named constants (including enumeration values) must be all uppercase using underscores to separate words **(I am not sure I like the uppercase here)**
7. Getters should have the name of the attribute. For instance, this->_objs should be accessed using this->objs()
8. Setters should start with “set_” followed by the name of the attribute. For instance: set_objs(const std::vector<float>& ov)
9. The public section should be the first section of a class
10. Type names defined using typedefs/aliases should end with _t (e.g. iterator_t)

I find it very close to my coding style and I want to adopt, but we would have to enforce it on the code somehow. We do not want to be too strict, but at least the base classes should follow the rules exactly. _I haven't checked if it is followed in the code, but I am assuming it's not followed everywhere._

What do you think?

**Comment by costashatz** [comment]
Any ideas on this?

**Comment by jbmouret** [comment]
I wrote them, therefore I am OK with them :)

**Comment by dogoepp** [comment]
I'm fine with it.

What bothers you with the point 6) ?

**Comment by costashatz** [comment]
> What bothers you with the point 6) ?

Nothing really. It's just that all caps seems like you are shouting. :stuck_out_tongue:

**Comment by jbmouret** [comment]
In classic C, we would write in caps, like 
#define MAGIC_NUMBER 1

However, we do not like caps in c++ and in the STL there is no caps.  We would have (c++-98): 
namespace xxx {
  static const int magic_number = 1;
}

in c++-11
namespace xxx {
  constexpr int magic_number = 1;
}

The cap is not typical here. We change use something else but have a sub-namespace �cst� maybe?
� JB

On 10 Dec 2015, at 14:29, Dorian Goepp <notifications@github.com> wrote:

> I'm fine with it.
> 
> What bothers you with the point 6) ?

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by dogoepp** [comment]
What's up with these recommendations ? I can add them in the wiki, bit I wonder if it would not be also good to have them in our public repos. For instance, it could be in a CONTRIBUTING file.

**Comment by costashatz** [comment]
What's the status on these recommendations?

**Comment by dogoepp** [comment]
They are in the wiki, but it would be nice to have them also either in a CONTRIBUTING file (or similar name) or in the documentation.

**Comment by costashatz** [comment]
@dogoepp do you have time to do it? or should we close this issue?

**Comment by dogoepp** [comment]
Will do

**Comment by dogoepp** [comment]
Done
