### ISSUE TITLE
remove the files created by CMA-ES

### ISSUE THREAD

**Issue by jbmouret** [resibots/limbo#48]

**Comment by fedeallocati** [comment]
Question, why not switch to a more modern and maintained cmaes library, like https://github.com/beniz/libcmaes ?

**Comment by jbmouret** [comment]
I would be OK for this.

-- JBM

Le ven. 11 déc. 2015 17:51, Federico Allocati <notifications@github.com> a
écrit :

**Comment by costashatz** [comment]
Me too. Who should do it?

**Comment by jbmouret** [comment]
I will.
� JBM
On 11 Dec 2015, at 18:21, Konstantinos Chatzilygeroudis <notifications@github.com> wrote:

> Me too. Who should do it?
> 
> �
> Reply to this email directly or view it on GitHub.
> 

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by fedeallocati** [comment]
Solved by #51
