### ISSUE TITLE
Make Multi-Objective optimisation compile in  the gp_multi branch

### ISSUE THREAD

**Issue by jbmouret** [resibots/limbo#5]
Do not forget to handle the blacklist.

**Comment by costashatz** [comment]
What's the status on this? I think it does compile. Does it run though?

**Comment by fedeallocati** [comment]
I think it doesn't even compile, because we aren't compiling any executable that uses any of them.

**Comment by jbmouret** [comment]
Yes, I should have a look at this next week.

� JBM

On 31 Oct 2015, at 13:01, Federico Allocati <notifications@github.com> wrote:

> I think it doesn't even compile, because we aren't compiling any executable that uses any of them.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by costashatz** [comment]
@jbmouret What is the status of this one?

**Comment by costashatz** [comment]
@jbmouret I think that you made this compile right?

**Comment by costashatz** [comment]
I am assuming that this is solved by @bpapaspyros work and I am closing it..
