### ISSUE TITLE
Init point in optimization of the acquisition function

### ISSUE THREAD

**Issue by jbmouret** [resibots/limbo#52]
In boptimizer.hpp:
```C++
AcquiOptimization(const AcquisitionFunction& acqui, const AggregatorFunction& afun, const Eigen::VectorXd& init) : _acqui(acqui), _afun(afun), _init(init) {}
```
... but it seems that the init is ignored:

```C++
double utility(const Eigen::VectorXd& params) const
{
        return _acqui(params, _afun);
}
```

So... either we make the  `opt` API capable of handing starting points, or we remove it here. Right?

**Comment by fedeallocati** [comment]
It is usted:

```
const Eigen::VectorXd& init() const
                {
                    return _init;
                }
```

The optimizers initialize the optimization with that point, and then call the utility function

**Comment by jbmouret** [comment]
Right. I did not look at the right place. Thx.
