### ISSUE TITLE
VERSION define

### ISSUE THREAD

**Issue by costashatz** [resibots/limbo#60]
What is the purpose of this [line](https://github.com/resibots/limbo/blob/gp_multi/src/limbo/bayes_opt/bo_multi.hpp#L3)?

**Comment by jbmouret** [comment]
Sferes needs a version number, usually provided on the command line via -DVERSION=�.

This is used to check that the results that are read have been written by the same version.

� JBM

On 16 Dec 2015, at 18:18, Konstantinos Chatzilygeroudis <notifications@github.com> wrote:

> What is the purpose of this line?
> 
> �
> Reply to this email directly or view it on GitHub.
> 

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by costashatz** [comment]
They are doing the same thing in libcmaes and it's causing conflicts.

**Comment by jbmouret** [comment]
This is (will be) part of the experimental part anyway (for multi-objective).

**Comment by costashatz** [comment]
OK. So we don't care. Closing this.
