### ISSUE TITLE
Update docs to new additions

### ISSUE THREAD

**Issue by costashatz** [resibots/limbo#64]
We should update the documentation (tutorials/guides) to follow the new additions.

**Comment by costashatz** [comment]
@fedeallocati You should update your doc pages to the new additions.

**Comment by dogoepp** [comment]
Without pressure, is there any news on this ?

**Comment by costashatz** [comment]
> Without pressure, is there any news on this ?

My examples should work with the newer additions. I have to check now that we changed the optimization API.

@fedeallocati ?

**Comment by fedeallocati** [comment]
Yeah, We have to adjust the parameters names in:

https://github.com/resibots/limbo/blob/gp_multi/docs/guides/parameters.rst
https://github.com/resibots/limbo/blob/gp_multi/docs/tutorials/basic_example.rst

Also, adjust the UML:
- Add the Init parameter in the optimizer operator's () signature
- Add the Model Hyper Parameters Optimization classes?

With that two things, I think the documentation will be up to date.

2016-01-14 10:05 GMT+01:00 Konstantinos Chatzilygeroudis <
notifications@github.com>:

**Comment by fedeallocati** [comment]
I have updated the parameter names in both of the docs. Is there anything else that is out of date?

**Comment by costashatz** [comment]
@jbmouret  UML? and call graph?

**Comment by jbmouret** [comment]
Yes, at least this. I will try to have a look at this next week.

**Comment by costashatz** [comment]
@jbmouret with #90 the docs were also updated or not?

**Comment by jbmouret** [comment]
I only worked on the API (including UML), I did not update the tutorials.

**Comment by jbmouret** [comment]
(I still need to include the Likelhood optimizers in the UML & call graph)
