### ISSUE TITLE
tools::rand is incorrect!

### ISSUE THREAD

**Issue by jbmouret** [resibots/limbo#65]

**Comment by costashatz** [comment]
Which of the 2?

This [one](https://github.com/resibots/limbo/blob/ed4fa763cd63ba839c7532f4e36d7df5097a521f/src/limbo/tools/math.hpp#L53) or this [one](https://github.com/resibots/limbo/blob/ed4fa763cd63ba839c7532f4e36d7df5097a521f/src/limbo/tools/math.hpp#L62)?

**Comment by jbmouret** [comment]
Sorry. It looks actually OK.

**Comment by costashatz** [comment]
What was your thought? Just curious.

**Comment by jbmouret** [comment]
It's written 'backwards' (see my comment above).
