### ISSUE TITLE
Init functions should be parallelized

### ISSUE THREAD

**Issue by jbmouret** [resibots/limbo#68]

**Comment by costashatz** [comment]
Since we are going to be using mostly robots with limbo, I am not sure parallelizing the init functions is a good idea. What do you think?

**Comment by fedeallocati** [comment]
As I told you, I agree with this. We would have to add mutexes to our evaluation code.

**Comment by costashatz** [comment]
@jbmouret What's your opinion?

**Comment by costashatz** [comment]
Maybe we should close this issue..

**Comment by fedeallocati** [comment]
+1

**Comment by jbmouret** [comment]
ok
