### ISSUE TITLE
check gp_auto

### ISSUE THREAD

**Issue by jbmouret** [resibots/limbo#8]
Line 51 of gp_auto:

LigGP uses: long double det = 2 * l.diagonal().array().log().sum(); 

But it could be (to compute the determinant): long double det = 2 * this->_kernel.diagonal().array().log().sum();

Is it the same?

**Comment by fedeallocati** [comment]
I may be wrong, buy if I recall correctly, the diagonal of the L in the cholesky factorization is not the same as the factorized matrix, so that 2 lines shouldn't give the same result

**Comment by jbmouret** [comment]
On 15 Oct 2015, at 18:40, Federico Allocati <notifications@github.com> wrote:

> I may be wrong, buy if I recall correctly, the diagonal of the L in the cholesky factorization is not the same as the factorized matrix, so that 2 lines shouldn't give the same result

I know. On the one hand, the equation says that we should use the kernel matrix; on the other hand, see here (line 253):
https://github.com/mblum/libgp/blob/master/src/gp.cc

Who is right? Did I miss some obvious optimisation?

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by fedeallocati** [comment]
The equations says that the determinant of the kernel matrix should be used, which is the same as 2 * l.diagonal().array().log().sum() (according to the link referenced in the code: http://xcorr.net/2008/06/11/log-determinant-of-positive-definite-matrices-in-matlab), which is what both limbo and libgp are using, so I think I'm not seeing the problem here

**Comment by jbmouret** [comment]
? The determinant of the kernel matrix should be `_kernel.diagonal().array().log().sum();` and not `2 * l.diagonal().array().log().sum();`

**Comment by fedeallocati** [comment]
All resources I'm finding say that the log determinant of a positive def. matrix is 2 * l.diagonal().array().log().sum(). I know that the equations say 0.5 * det(kernel_maktrix).
I can't find anywhere that says that the log determinant of the kernel matrix should be the sum of the logs of it's diagonal

**Comment by jbmouret** [comment]
Oh, I see. Sorry, you are right. The current code (that I wrote!) is right. I just did not remember the actual formula...
