### ISSUE TITLE
BOptimizer named parameters bug

### ISSUE THREAD

**Issue by fedeallocati** [resibots/limbo#81]
A bug was introduced in one of the last PR, and now if 6 named parameter are passed to the `BOptimizer`, the last one doesn't get passed to `BoBase`. This can be a problem if the last one is not `acquiopt`.
For example, if someone specifies 6 parameters, and the last one is `stopcrit`, it will be ignored, because it's not passed to `BoBase`, and defaults will be used instead.

**Comment by costashatz** [comment]
Fixed in #122 ...
