### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by costashatz** [resibots/limbo#94]
We should add CI to the library..

**Comment by dogoepp** [comment]
This is going to be an interesting discussion.

Right now, we can use two CI systems at INRIA and there is a high 
probability that at least one of those will stop working in October. 
Maybe we could discuss this next Wednesday ?

**Comment by costashatz** [comment]
A first step was done with #97.. I am closing this issue for the moment and we should reopen it when gitlab and INRIA implement something that can suit our needs..
